In [1]:
# 1. Import pandas and numpy library.

import numpy as np
import pandas as pd

In [2]:
# 2. Read the RadNet dataset from the U.S. Environmental Protection Agency.

df = pd.read_csv("RadNet_Laboratory_Analysis.csv")

In [3]:
# 3. Create a list with numeric columns for radionuclides in the RadNet dataset.

# df.head()
numeric = df.iloc[:,6:]
numeric_list = list()
for i in numeric:
    numeric_list.append(i)
print(*numeric_list, sep = ", ")

Ba-140, Co-60, Cs-134, Cs-136, Cs-137, I-131, I-132, I-133, Te-129, Te-129m, Te-132

In [4]:
# 4. Use the apply method on one column, with a lambda function that compares the Non-detect
# string

df['Ba-140'] = df['Ba-140'].apply(lambda x: np.nan if x == "Non-detect" else x)

In [5]:
# 5. Use applymap method to replace text values "Non-detect" with .np.nan in all numeric
# columns at once, do the same with "ND" value

df.iloc[:, :] = df.iloc[:, :].applymap(lambda x: np.nan if x == 'Non-detect' else x)
df.iloc[:, :] = df.loc[:, :].applymap(lambda x: np.nan if x == 'ND' else x)

df.head(10)

,State,Location,Date Posted,Date Collected,Sample Type,Unit,Ba-140,Co-60,Cs-134,Cs-136,Cs-137,I-131,I-132,I-133,Te-129,Te-129m,Te-132
0,ID,Boise,03/30/2011,03/23/2011,Air Filter,pCi/m3,NaN,NaN,NaN,NaN,NaN,0.088,NaN,NaN,NaN,NaN,NaN
1,ID,Boise,03/30/2011,03/23/2011,Air Filter,pCi/m3,NaN,NaN,NaN,NaN,NaN,0.055,NaN,NaN,NaN,NaN,NaN
2,AK,Juneau,03/30/2011,03/23/2011,Air Filter,pCi/m3,NaN,NaN,0.0057,NaN,0.0074,0.067,NaN,NaN,NaN,NaN,0.0043
3,AK,Nome,03/30/2011,03/22/2011,Air Filter,pCi/m3,NaN,NaN,NaN,NaN,NaN,0.096,NaN,NaN,NaN,NaN,NaN
4,AK,Nome,03/30/2011,03/23/2011,Air Filter,pCi/m3,NaN,NaN,NaN,NaN,NaN,0.22,NaN,NaN,NaN,NaN,NaN
5,AK,Nome,03/30/2011,03/23/2011,Air Filter,pCi/m3,NaN,NaN,0.016,NaN,0.023,0.2,0.019,NaN,NaN,NaN,0.027
6,AK,Nome,04/04/2011,03/24/2011,Air Filter,pCi/m3,NaN,NaN,0.14,NaN,0.12,0.43,0.094,NaN,NaN,NaN,0.14
7,AK,Nome,04/04/2011,03/24/2011,Air Filter,pCi/m3,NaN,NaN,0.1,0.012,0.13,0.39,0.076,NaN,0.12,0.061,0.12
8,HI,Oahu,03/30/2011,03/20/2011,Air Filter,pCi/m3,NaN,NaN,0.034,NaN,0.021,0.2,NaN,NaN,NaN,NaN,NaN
9,HI,Oahu,03/30/2011,03/20/2011,Air Filter,pCi/m3,NaN,NaN,0.028,NaN,0.036,0.14,0.02,NaN,NaN,NaN,0.029

In [8]:
# 6. Use the same applymap method to remove all spaces (from begining and end) in all other
# columns (non-numeric). Use strip() method to remove spaces.

# df.dtypes

not_numeric = df.iloc[:,:6]
not_numeric_list = list()
for i in not_numeric:
    not_numeric_list.append(i)
print(*not_numeric_list, sep = ", ")

for i in not_numeric_list:
    df[i]=df[i].astype('string')

df.iloc[:, :6] = df.iloc[:, :6].apply(lambda x: x.strip() if x.dtype=='String' else x)

State, Location, Date Posted, Date Collected, Sample Type, Unit

In [11]:
# 7. Change datatypes of columns using methods (use df.dtypes() to check datatypes):

df.dtypes

# pd.to_datetime()
# pd.to_numeric()

date_type = df.iloc[:,2:4]
date_type_list = list()
for i in date_type:
    date_type_list.append(i)
    
for i in date_type_list:
    df[i] = pd.to_datetime(df[i])

for j in numeric_list:
    df[j] = pd.to_numeric(df[j])

df.dtypes

State                     string
Location                  string
Date Posted       datetime64[ns]
Date Collected    datetime64[ns]
Sample Type               string
Unit                      string
Ba-140                   float64
Co-60                    float64
Cs-134                   float64
Cs-136                   float64
Cs-137                   float64
I-131                    float64
I-132                    float64
I-133                    float64
Te-129                   float64
Te-129m                  float64
Te-132                   float64
dtype: object